### ISSUE TITLE
Lỗi gởi tự động bn nội trú có lập toa ngoại trú (BV Tâm Phúc)

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalservices#10]
Lỗi gởi tự động bn điều trị nội trú có lập toa ngoại trú  không thanh bhyt (BV Tâm Phúc)
Service đẩy cổng loại hồ sơ là ngoại trú và không đúng chi phí !

Dữ liệu: dbtamphuc

**Comment by hvtuan1987** [comment]
Kiểm dùm em dữ liệu này anh Hậu ơi ! BV mới nhắc nữa á

**Comment by ongtrieuhau** [comment]
Cập nhật tại [v3.22.0701.2](https://github.com/dh-hos/dhg.hospitalservices/commit/1de29c6c01a03f9109d31d30e2d2dd9a56a24e4a)
