### ISSUE TITLE
Yêu cầu - Thực hiện mô tả công văn 31/BHXH

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalservices#16]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/04/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `ALL`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

```
[chi_tiet_yeu_cau](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

```

**Comment by nghivanbi** [comment]
Này xong chưa @ongtrieuhau ?

**Comment by ongtrieuhau** [comment]
> Này xong chưa @ongtrieuhau ?

Cập nhật 
- Admin [3.23.0504.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/8ef4737631babe6f05de448cae4660f73644fb9c)
- Services [3.23.0504.1](https://github.com/dh-hos/dhg.hospitalservices/commit/99efa3aa50187448a2059d1bc9d8b00fe15d1109)

**Comment by le-an-87** [comment]
đã cập nhật!

**Comment by nghivanbi** [comment]
Hiệu chỉnh theo mô tả cập nhật: https://github.com/dh-hos/Mo-ta-he-thong/issues/24#issuecomment-1547187561

**Comment by ongtrieuhau** [comment]
Cập nhật Services [3.23.0515.1](https://github.com/dh-hos/dhg.hospitalservices/commit/1520672fe592774fdfb184f47c7235d8de66e363)

**Comment by le-an-87** [comment]
Đã cập nhật theo mô tả!

**Comment by nghivanbi** [comment]
@ongtrieuhau , @le-an-87 hỗ trợ bổ sung mô tả hỗ trợ yêu cầu BV Phụ Sản CT.

**Comment by ongtrieuhau** [comment]
Thực hiện lại theo [thay đổi ngày 13/06/2023](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)

**Comment by ongtrieuhau** [comment]
Cập nhật 
-  Admin: [3.23.0616.1](https://github.com/dh-hos/dhg.hospitaladmin/commit/efe8dcb1752974e4bba8431e1948180d388a4ef8)
- Services: [3.23.0616.1](https://github.com/dh-hos/dhg.hospitalservices/commit/eac0fffa3e2c4209cabab41585370340bb74ae1f)

**Comment by le-an-87** [comment]
alo anh @ongtrieuhau ơi
![image](https://github.com/dh-hos/dhg.hospitalservices/assets/96155021/ed34925d-bff6-4d51-b1e4-fd7665da4417)
em kiểm tra chức năng xuất xml thì chưa load được theo tham số mới anh ơi!

**Comment by ongtrieuhau** [comment]
Cập nhật lại nhé @le-an-87 

- Admin: [3.23.0616.2](https://github.com/dh-hos/dhg.hospitaladmin/commit/67aa3433a94b1b761c902ff17e838bb14de9d173)
- Services: [3.23.0616.2](https://github.com/dh-hos/dhg.hospitalservices/commit/09c2d1449de9cfc4240662d91c97be2d2ed3b814)

**Comment by le-an-87** [comment]
Đã bổ sung theo [mô tả!](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML4210/20230415-Hau-CV1731-BHXH-G%C4%90%C4%90T-Thanh-toan-phau-thuat-vo-cam-gay-te.md)
