### ISSUE TITLE
Yêu cầu - Thực hiện mô tả hỗ trợ gởi XML với bệnh nhân B20

### ISSUE THREAD

**Issue by nghivanbi** [dh-hos/dhg.hospitalservices#17]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Nghị Văn Bi**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **05/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `ten_csdl`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

```
chi_tiet_yeu_cau
[mã hóa mã loại kcb HIV-cấp thuốc HIV.BHXHVN.pdf](https://github.com/dh-hos/dhg.hospitalservices/files/11648202/ma.hoa.ma.lo.i.kcb.HIV-c.p.thu.c.HIV.BHXHVN.pdf)

```

**Comment by le-an-87** [comment]
em gửi dữ liệu test đó anh @ongtrieuhau!
tên data: an_omon_b20_issues_services_17
mã khoa: 008
mã phòng: PL
ngày khám cuối: 05/06/2023
mabn: 2022018490
mã kb: 2306002755
mã ba: N2022001800
[link data an_omon_b20_issues_services_17](https://gofile.me/78TQg/9GtbnVzsJ)
![image](https://github.com/dh-hos/dhg.hospitalservices/assets/96155021/e18d9edc-8e17-49f5-aa2c-ed23e5fc4058)

**Comment by ongtrieuhau-dh** [comment]
Cái này close luôn nhé a @nghivanbi vì nằm trong 4750 rồi

**Comment by ongtrieuhau-dh** [comment]
Đóng lại, vì đã thực thực 4750
