### ISSUE TITLE
Lỗi - Gửi cổng bệnh nhân đã mở khóa chứng từ.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalservices#20]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **21/11/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **TTYT Phước Long BLI**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_phuoclong_bl_phieuthusaichitiet`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023016875` - _**MaKB**_: `2309004509` - _**MaBA**_: `MaBA` _**NgayKCB**_: `21/11/2023` - _**MaPhong**_: `09` - _**MaDV**_: `02` - _**ThangKT**_: `09` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Printer BN đã được in phiếu sau đó **Mở khóa chứng từ**, thời gian từ khi in phiếu đến mở khóa thì module Services chưa gủi cổng do chưa tới thời gian gửi theo cấu hình.
Sau khi mở khóa ra thì module Services lại gửi BN này lên cổng giám định, và nó gủi liên tục luôn => cổng xuất hiện nhiều HS lỗi.
Bản mới nhất đã cập nhật lỗi này 1 lần rồi nhưng vẫn còn bị tình trạng trên.
![image](https://github.com/dh-hos/dhg.hospitalservices/assets/99630883/bf17aa2c-e81a-4097-881f-fda7b4159118)

**Comment by ongtrieuhau-dh** [comment]
Hiện tại chỗ gửi này chỉ quan tâm tới thời gian in phiếu, nên nếu không muốn gửi thì phải xóa thời gian in phiếu trên Printer luôn nhé

**Comment by lqbinh1987** [comment]
OK anh, em đã nắm được thông tin, để em báo lại BV.
