### ISSUE TITLE
Lỗi - Service không đẩy tự động Bảng 4 Siêu âm, XQ, ĐT

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/dhg.hospitalservices#21]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Đức**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **04/12/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `51014`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Quãng Ngãi**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `duc_quangngai_bang4`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`] https://gofile.me/78TQg/aUWD3ipb6

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2021004281` - _**MaKB**_: `2311010475` - _**MaBA**_: `MaBA` _**NgayKCB**_: `30/11/2023` - _**MaPhong**_: `A1-17` - _**MaDV**_: `10` - _**ThangKT**_: `11` - _**NamKT**_: `2023`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Report Bảng 4 có load kết quả Xét nghiệm, Diag (SA, Điện tim, XQ) 
Mà Service đẩy tự động lên cổng thì chỉ đẩy kết quả Xét nghiệm. **Kết quả Diag (SA, Điện tim, XQ) không đẩy được**

```
Dữ liệu Trên Report bảng 4 
![image](https://github.com/dh-hos/dhg.hospitalservices/assets/98437757/5127b5b3-e9da-40ad-a066-9e6842edad12)

Dữ liệu trên Admin - Kiểm tra xuất xml
![image](https://github.com/dh-hos/dhg.hospitalservices/assets/98437757/a0cf2a5d-8d0f-4c10-ae71-fc4288145780)

**Comment by nghivanbi** [comment]
@ongtrieuhau kiểm tra fix lỗi này nhé, các bệnh viện bị kiểm tra xuất toán.

**Comment by minhduc2it** [comment]
anh @ongtrieuhau fix dùm em sớm lỗi này nha, bệnh viện đang chờ để gửi tự động
