### ISSUE TITLE
Gửi dữ liệu XML tự động - Tính lại tỷ lệ thanh toán

### ISSUE THREAD

**Issue by ongtrieuhau** [dh-hos/dhg.hospitalservices#4]
Theo biên bản họp tuần [**DH_HopTuan_20220509.pdf**](https://github.com/oth-dhghospital/dhg.hospitalservices/files/8657405/DH_HopTuan_20220509.pdf)
Gửi dữ liệu XML tự động: Trường hợp VTYT thanh toán theo tỷ lệ chức năng gửi tự động tự tính lại tỷ lệ nên gửi lên cổng bhxh báo lỗi.
Đề nghị cung cấp dữ liệu để kiểm tra lại. @le-an-87

**Comment by le-an-87** [comment]
em gửi tên data: an_omon_guitudong_tinhlaityle
![image](https://user-images.githubusercontent.com/96155021/168204476-1a11a5ec-dfcd-45ef-b894-0780b933c702.png)

VTYT tại xuất ở Reports
![image](https://user-images.githubusercontent.com/96155021/168204686-b043801d-387f-42b3-bf35-8e9136d5944d.png)

Trần thanh toán và tỷ lệ của VTYT
![image](https://user-images.githubusercontent.com/96155021/168204890-c48a79a8-b320-44a1-93cf-6122f0a5ebe1.png)

**Comment by ongtrieuhau** [comment]
Hãy sử dụng chức năng này để lấy giá BHYT khi thanh toán nhé @le-an-87 
![image](https://user-images.githubusercontent.com/58720300/175228626-57ef8e0f-1550-41d0-aa48-7747890418ce.png)
