### ISSUE TITLE
Gửi tự động, XML thiếu mã BS thực hiện CLS.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalservices#6]
Gửi tự động thiếu mã bác sĩ như mô tả ở issue bên Module Admin.
https://github.com/oth-dhghospital/dhg.hospitaladmin/issues/13

**Comment by o-ngtrieuhau861gmailcom** [comment]
Cập nhật tại đây 5a6462e9dd48622be1492fa8a41190aa55bb811b
