### ISSUE TITLE
Service gửi những những BN đã trả về điều trị.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalservices#9]
BN đã xuất viện, dữ liệu được tạo trong bảng psxml đã ok, lúc này service chưa gửi tự động kịp, sau đó trả về điều trị cho BN đó, thì module Admin vẫn lấy lên được dữ liệu XML của BN do dữ liệu của BN đó vẫn còn trong bảng psxml, nhưng khi xem XML1,2,3,4,5 thì cái mã liên kết không đúng cấu trúc, bị thiếu **namrv** và **thangrv**(hình bên dưới), lúc này service vẫn gửi XML này lên cổng tiếp nhận với mã liên kết bị sai lun.
Đến khi kết thúc BN đó lại thì service lại gửi thêm lần nữa với mã liên kết đúng. => phát sinh % sai sót(những hồ sơ bị sai mã liên kết) trên cổng tiếp nhận.

Data: binh_thanhtri_malk____
Mã BA: 2022003079.

![image](https://user-images.githubusercontent.com/99630883/174729551-84644575-7dc0-4fc1-9cfe-3e635bbc4c15.png)

**Comment by ongtrieuhau** [comment]
Phần này kiểm tra kỹ lại trường hợp nhé và phiên bản services đang chạy, vì trong code đã loại trừ những mã liên kết nào có dấu `__`  là sẽ không gửi

**Comment by lqbinh1987** [comment]
Anh @ongtrieuhau.
Nhờ a Hậu coi lại dùm em, em test lại rồi nhưng nó vẫn bị trình trạng trên, cái mã liên kết có 3 dấu `_` liên tục là `___` nó xuất hiện trong XML1,2,3,4,5 chưa không phải trong cột **psxml.ma_lk**
![image](https://user-images.githubusercontent.com/99630883/188534513-1c8e779e-f5e3-4bf6-b9e7-856d4ed717b8.png)

**Comment by ongtrieuhau** [comment]
Cho xin thông tin dữ liệu cụ thể ngay bệnh nhân nào để kiểm tra lại nhé @lqbinh1987
